version: '2'

tasks:
  mesos:
    dir: mesos
    cmds:
      - echo "Building Mesos ..."
      - docker build --compress --build-arg VERSION={{.VERSION}} -t andersnormal/mesos .
      - docker tag andersnormal/mesos andersnormal/mesos:{{.VERSION}}
      - docker push andersnormal/mesos:{{.VERSION}}
    vars:
      VERSION:
        sh: git describe --exact-match --tags $(git log -n1 --pretty='%h')
  master:
    dir: master
    cmds:
      - echo "Building Mesos Master ..."
      - docker build --compress --build-arg MESOS_IMAGE=andersnormal/mesos:{{.VERSION}} --build-arg VERSION={{.VERSION}} -t andersnormal/mesos-master .
      - docker tag andersnormal/mesos-master andersnormal/mesos-master:{{.VERSION}}
      - docker push andersnormal/mesos-master:{{.VERSION}}
    vars:
      VERSION:
        sh: git describe --exact-match --tags $(git log -n1 --pretty='%h')
  agent:
    dir: agent
    cmds:
      - echo "Building Mesos Agent ..."
      - docker build --compress --build-arg MESOS_IMAGE=andersnormal/mesos:{{.VERSION}} --build-arg VERSION={{.VERSION}} -t andersnormal/mesos-agent .
      - docker tag andersnormal/mesos-agent andersnormal/mesos-agent:{{.VERSION}}
      - docker push andersnormal/mesos-agent:{{.VERSION}}
    vars:
      VERSION:
        sh: git describe --exact-match --tags $(git log -n1 --pretty='%h')
  exhibitor:
    dir: exhibitor
    cmds:
      - echo "Building Exhibitor ..."
      - docker build --compress --build-arg EXHIBITOR_VERSION={{.EXHIBITOR_VERSION}} --build-arg ZOOKEEPER_VERSION={{.ZOOKEEPER_VERSION}} -t andersnormal/exhibitor .
      - docker tag andersnormal/exhibitor andersnormal/exhibitor:{{.VERSION}}
      - docker push andersnormal/exhibitor:{{.VERSION}}
    vars:
      EXHIBITOR_VERSION: "1.7.1"
      ZOOKEEPER_VERSION: "3.4.13"
  build:
    cmds:
      - task: mesos
      - task: master
      - task: agent
      - task: exhibitor